---
services:
  webdav-nginx:
    container_name: webdav-nginx
    build:
      context: '../../images/nginx'
    restart: 'unless-stopped'
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf:ro'
      - './sockets:/sockets'
      - './rw:/rw:U'
    environment: {}

