---
services:
  nginx:
    container_name: webdav
    image: 'dgraziotin/nginx-webdav-nononsense:1.28.0'
    restart: 'unless-stopped'
    volumes:
      - './data:/data'
      - './config:/config'
      - './sockets:/sockets'
    environment:
      WEBDAV_USERNAME: ${WEBDAV_USERNAME}
      WEBDAV_PASSWORD: ${WEBDAV_PASSWORD}
      PUID: ${PUID}
      PGID: ${PGID}

