---
services:
  nginx:
    container_name: hello-world-nginx
    build:
      context: '../../images/nginx'
    restart: 'unless-stopped'
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf:ro'
      - './sockets:/sockets'
    environment: {}

